stolostron/console-chart

- .travis.yml
https://github.com/open-cluster-management/backlog/issues/9783
> #9783: update mch repo's default branch for auto-trigger build

- stable/console-chart/templates/_helpers.tpl
- stable/console-chart/templates/clusterimageset-clusterrole.yaml
- stable/console-chart/templates/clusterimageset-clusterrolebinding.yaml
- stable/console-chart/templates/console-clusterrole.yaml
- stable/console-chart/templates/console-clusterrolebinding.yaml
- stable/console-chart/templates/console-deployment.yaml
- stable/console-chart/templates/console-header-configmap.yaml
- stable/console-chart/templates/console-header-deployment.yaml
- stable/console-chart/templates/console-header-ingress-welcome.yaml
- stable/console-chart/templates/console-header-ingress.yaml
- stable/console-chart/templates/console-header-log-config.yaml
- stable/console-chart/templates/console-header-service.yaml
- stable/console-chart/templates/console-ingress.yaml
- stable/console-chart/templates/console-service.yaml
Correct early version of copyright statement to use the more recent copyright
> fix copyright

- stable/console-chart/templates/console-clusterrole.yaml
https://github.com/open-cluster-management/backlog/issues/10240
> Update clusterrole to watch discoveryconfig

- README.md
- stable/console-chart/templates/console-header-ingress.yaml
- stable/console-chart/templates/console-ingress.yaml
For issue https://github.com/open-cluster-management/backlog/issues/10925
> Ingress upgrade to networking.k8s.io/v1

- stable/console-chart/templates/console-deployment.yaml
Signed-off-by: James Talton <jtalton@redhat.com>
> fix console route env variables

- stable/console-chart/templates/console-clusterrole.yaml
Signed-off-by: randybrunopiverger <rbrunopi@redhat.com>
> adding cluster curator resource to chart

- stable/console-chart/templates/channel.yaml
Signed-off-by: Joshua Packer <jpacker@redhat.com>
* In 2.3 @rokej introduced a reconcile rate. Using low reduces our check to hourly.
> Set the reconcile rate to low

- .copyrightignore
- .github/workflows/fast-forward.yml
- .github/workflows/helm-lint.yml
- .github/workflows/push-chart.yml
- Makefile
- SECURITY.md
- build/before-make.sh
- build/check-copyright.sh
- build/copyright-header.txt
- build/githooks/commit-msg
- build/githooks/pre-commit
For issue https://github.com/open-cluster-management/backlog/issues/11341
> Add dco support

- stable/console-chart/templates/console-deployment.yaml
Signed-off-by: James Talton <jtalton@redhat.com>
> console livenessProbe

- README.md
- stable/console-chart/templates/console-configmap.yaml
- stable/console-chart/templates/console-deployment.yaml
For issue https://github.com/open-cluster-management/backlog/issues/12158
> Add configmap parameters for console

- stable/console-chart/templates/img4.6.28-x86_64.yaml
- stable/console-chart/templates/img4.7.11-x86_64.yaml
For issue https://github.com/open-cluster-management/backlog/issues/12657
> update OCP 4.6 and 4.7 versions

- stable/console-chart/templates/console-clusterrole.yaml
Signed-off-by: Sho Weimer <sweimer@redhat.com>
> Add SubmarinerConfig to cluster role

- stable/console-chart/Chart.yaml
Final piece for https://github.com/open-cluster-management/backlog/issues/12925
> need to update 2.0 chart version when changes go in

- stable/console-chart/templates/console-clusterrole.yaml
Signed-off-by: Sho Weimer <sweimer@redhat.com>
> Add ManagedClusterSetBindings to SA permissions

- stable/console-chart/templates/console-clusterrole.yaml
Signed-off-by: randybrunopiverger <rbrunopi@redhat.com>
regarding: https://github.com/open-cluster-management/backlog/issues/13131
> ansiblejobs get, list, watch, permission for console

- stable/console-chart/templates/img4.6.36-x86_64.yaml
- stable/console-chart/templates/img4.7.18-x86_64.yaml
For https://github.com/open-cluster-management/backlog/issues/13915
> update OCP releases in ACM 2.1

- stable/console-chart/Chart.yaml
Part b for issue https://github.com/open-cluster-management/backlog/issues/13915
> Need to update chart version z value for change to be picked up

- stable/console-chart/templates/console-configmap.yaml
Signed-off-by: James Talton <jtalton@redhat.com>
> console configmap feature flags

- stable/console-chart/templates/console-clusterrole.yaml
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>
> Bug 16892: Fix BMH apiGroup

- stable/console-chart/templates/console-deployment.yaml
Signed-off-by: Kevin Cormier <kcormier@redhat.com>
https://github.com/open-cluster-management/backlog/issues/17388
> Add proxy environment for console

- stable/console-chart/templates/subscription-fast.yaml
Signed-off-by: root <daliu@redhat.com>
> use relase branch in clusterimageset subscription

- stable/console-chart/templates/subscription-fast.yaml
https://github.com/open-cluster-management/backlog/issues/17849
> use release-2.3 branch in clusterimageset subscription

- stable/console-chart/templates/subscription-fast.yaml
https://github.com/open-cluster-management/backlog/issues/17849
> use release-2.2 branch in clusterimageset subscription

- stable/console-chart/templates/console-clusterrole.yaml
Signed-off-by: Maggie Chen <magchen@redhat.com>
> Add permissions for placements

- Makefile
- stable/console-chart/values.yaml
stolostron/backlog#18707
stolostron/backlog#18716
> Update GH org to stolostron

- .travis.yml
- Makefile
- stable/console-chart/values.yaml
https://github.com/stolostron/backlog/issues/18707
https://github.com/stolostron/backlog/issues/18716
> [release-2.2] Update GH org to stolostron

- Makefile
- stable/console-chart/values.yaml
stolostron/backlog#18707
stolostron/backlog#18716
> [release-2.3] Update GH org to stolostron

- Makefile
- stable/console-chart/values.yaml
stolostron/backlog#18707
stolostron/backlog#18716
> [release-2.4] Update GH org to stolostron

- .github/workflows/push-chart.yml
- CONTRIBUTING.md
- README.md
> More stolostron updates

- .github/workflows/push-chart.yml
- CONTRIBUTING.md
- README.md
> [release-2.4] More stolostron updates

- .github/workflows/push-chart.yml
- CONTRIBUTING.md
- README.md
> [release-2.3] More stolostron updates

- stable/console-chart/templates/console-plugin.yaml
https://github.com/stolostron/backlog/issues/19171
> Use proxy alias

- stable/console-chart/templates/console-ingress.yaml
Signed-off-by: Kevin Cormier <kcormier@redhat.com>
https://github.com/stolostron/backlog/issues/19742
> Add path for / to Ingress

- stable/console-chart/templates/console-deployment.yaml
- stable/console-chart/values.yaml
Signed-off-by: Ray Harris <raharris@redhat.com>
Chart update needed for MCH to pass tolerations to deployments:
https://github.com/stolostron/backlog/issues/9274
> allow toleration override on deployment

- stable/console-chart/templates/_helpers.tpl
- stable/console-chart/templates/console-plugin.yaml
- stable/console-chart/values.yaml
- Add ocpVersion instead of plugin value
- Remove unused values
- Update plugin name
Signed-off-by: Kevin Cormier <kcormier@redhat.com>
> Updates for splitting plugin into ACM/MCE

- stable/console-chart/templates/_helpers.tpl
- stable/console-chart/values.yaml
Signed-off-by: Zachary Kayyali <zkayyali@redhat.com>
> Refactor ocpVersion under hubconfig

- stable/console-chart/templates/console-clusterrole.yaml
Signed-off-by: Zack Layne <zlayne@redhat.com>
> Add PlacementDecisions to console-clusterrole

- stable/console-chart/templates/console-clusterrole.yaml
Signed-off-by: Zack Layne <zlayne@redhat.com>
Related issue: https://github.com/stolostron/backlog/issues/20730
> Add subscription operator to clusterrole

- stable/console-chart/templates/console-clusterrole.yaml
https://github.com/stolostron/backlog/issues/22406
> Add permission for nmstateconfigs for agent-install.openshift.io

- stable/console-chart/templates/console-clusterrole.yaml
Signed-off-by: Zack Layne <zlayne@redhat.com>
Related issue: https://github.com/stolostron/backlog/issues/22961
> Remove wildcard permission from clusterrole

- stable/console-chart/templates/subscription-fast.yaml
Signed-off-by: ldpliu <daliu@redhat.com>
https://github.com/stolostron/backlog/issues/23927
> use release-2.6 clusterimageset

- stable/console-chart/templates/console-clusterrole.yaml
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>
> Add permissions to list/watch resources needed for hypershift

- stable/console-chart/templates/console-plugin.yaml
https://github.com/stolostron/backlog/issues/24467
> [release-2.5] Add annotation to enable i18n in 4.11+

- stable/console-chart/templates/console-plugin.yaml
https://github.com/stolostron/backlog/issues/24467
> Add annotation to enable i18n in 4.11+

- stable/console-chart/templates/console-clusterrole.yaml
Required by https://github.com/stolostron/console/pull/1968
> Add permissions to list/watch multiclusterengine resources

- stable/console-chart/templates/console-ingress.yaml
https://issues.redhat.com/browse/ACM-3043
> ACM-3043 Remove annotation (not allowed when spec.ingressClassName set)

- stable/console-chart/templates/console-ingress.yaml
Revert changes for:
https://issues.redhat.com/browse/ACM-3043
> ACM-3043 Remove ingress fix

- stable/console-chart/templates/console-ingress.yaml
> ACM-3034 Restore ingress annotation
